name: 'my_dbt_project' # Replace with your project name
version: '1.0.0'
config-version: 2

profile: 'my_snowflake_profile' # Matches the profile name in profiles.yml

model-paths: ["models"]   # Folder where your SQL models are stored
analysis-paths: ["analyses"] # Folder for ad-hoc SQL queries
test-paths: ["tests"]     # Folder for data tests
seed-paths: ["seeds"]     # Folder for seed files
macro-paths: ["macros"]   # Folder for custom macros
snapshot-paths: ["snapshots"] # Folder for snapshot models

target-path: "target"     # Folder for compiled SQL and run results
clean-targets:
  - "target"
  - "dbt_packages"

